fix: xkeysnail-monitor start xkeysnail failed if it run in console

diff --git a/bin/xkeysnail-monitor b/bin/xkeysnail-monitor
--- a/bin/xkeysnail-monitor
+++ b/bin/xkeysnail-monitor
@@ -5,13 +5,14 @@ if [ -z "$SCRIPT_PATH" ]; then
   SCRIPT_PATH="${BASH_SOURCE[0]}"
 fi
 SCRIPT_NAME=$(basename "${SCRIPT_PATH}")
-SCRIPT_PATH_MD5=$(echo -n "${SCRIPT_PATH}" | md5sum | awk '{print $1}')
-SCRIPT_LOCK_FILE="/tmp/${SCRIPT_NAME}.${SCRIPT_PATH_MD5}.lock"
+LOCK_FILE="/tmp/${SCRIPT_NAME}.lock"
+LOG_FILE="${LOG_FILE:-/dev/null}"
 
-if [ -z "$FLOCK" ]; then
-  touch "${SCRIPT_LOCK_FILE}"
-  export FLOCK=${SCRIPT_LOCK_FILE}
-  exec flock -x -n "${SCRIPT_LOCK_FILE}" -c "${SCRIPT_PATH}"
+if [ -z "$XKEYSNAIL_MONITOR_LOCKED" ]; then
+  # Modify LOCK_FILE for wakeup xkeysnail-monitor
+  echo -e "$(date)\tWakeup xkeysnail-monitor" | tee ${LOCK_FILE} >>${LOG_FILE}
+  export XKEYSNAIL_MONITOR_LOCKED="${LOCK_FILE}"
+  exec flock -x -n "${LOCK_FILE}" -c "${SCRIPT_PATH}"
   exit $?
 fi
 
@@ -21,6 +22,7 @@ capslock_off() {
     setcapslock off
   fi
   setleds -caps
+  echo -e "$(date)\tCapsLock off" >>${LOG_FILE}
 }
 
 while [ true ]; do
@@ -31,18 +33,20 @@ while [ true ]; do
     if [ "$(~/bin/tty-ctl graphic)" = "$(~/bin/tty-ctl active)" ]; then
       if ~/bin/keymap-ctl status >/dev/null 2>&1; then
         ~/bin/keymap-ctl stop
+        echo -e "$(date)\tStop keymap" >>${LOG_FILE}
       fi
       if ! ~/bin/xkeysnail-ctl status >/dev/null 2>&1; then
-        echo -e "$(date)\tStart xkeysnail"
+        echo -e "$(date)\tStart xkeysnail" >>${LOG_FILE}
         ~/bin/xkeysnail-ctl start
       fi
     fi
   else
     if ~/bin/xkeysnail-ctl status >/dev/null 2>&1; then
-      echo -e "$(date)\tStop xkeysnail"
+      echo -e "$(date)\tStop xkeysnail" >>${LOG_FILE}
       ~/bin/xkeysnail-ctl stop
     fi
     if ! ~/bin/keymap-ctl status >/dev/null 2>&1; then
+      echo -e "$(date)\tStart keymap" >>${LOG_FILE}
       ~/bin/keymap-ctl start
     fi
   fi
@@ -51,10 +55,11 @@ while [ true ]; do
 
   TTY_ACTIVE_CURRENT=$(cat /sys/class/tty/tty0/active)
   if [ "${TTY_ACTIVE_PREVIOUS}" = "${TTY_ACTIVE_CURRENT}" ]; then
-    if ! inotifywait -q -e modify /sys/class/tty/tty0/active >/dev/null 2>&1; then
-      echo -e "$(date)\tinotifywait failed: $?" >/dev/stderr
+    if ! inotifywait -q -e modify /sys/class/tty/tty0/active "${LOCK_FILE}" >/dev/null 2>&1; then
+      echo -e "$(date)\tinotifywait failed: $?" >>${LOG_FILE}
       sleep 10
     fi
   fi
   TTY_ACTIVE_PREVIOUS=${TTY_ACTIVE_CURRENT}
+  echo -e "$(date)\tinotifywait successed" >>${LOG_FILE}
 done
